import { useState, useMemo, useEffect, useRef } from "react";

const LANGS = {
  es:{ tag:"ES", flag:"🇪🇸", smartEnergy:"Energía Inteligente", title1:"CALCULA TU", title2:"AHORRO ENERGÉTICO", sub:"Diseña tu sistema solar y ve cuánto ahorras al mes.", step1:"Paso 1", step1t:"Tu factura actual", billLabel:"Factura mensual promedio", rateLabel:"Tarifa de energía (por kWh)", rateHint:"Colombia ≈ 620 COP · México ≈ 1.1 MXN · España ≈ 0.25 EUR", step2:"Paso 2", step2t:"Tus electrodomésticos", step2sub:"Selecciona cada equipo y personaliza su uso diario.", addBtn:"Agregar", removeBtn:"Quitar", hoursLabel:"Horas/día", qtyLabel:"Cant.", step3:"Paso 3", step3t:"Tu ubicación solar", pshLabel:"Horas de sol pico al día (HSP)", pshHint:"Colombia ≈ 4–5 · Costa/Llanos ≈ 5.5–6 · España ≈ 4.5–6", step4:"Paso 4", step4t:"Elige tu plan solar", planNote:"Recomendado según tu consumo. Puedes ajustar.", calcBtn:"⚡ VER MI AHORRO", err:"Ingresa tu factura mensual", savingsMonth:"Ahorro mensual estimado", savingsYear:"Ahorro anual", savings25:"Ahorro 25 años", coverageLbl:"Cobertura solar", genLbl:"Generación/mes", consumLbl:"Consumo/mes", paybackLbl:"Retorno inversión", costLbl:"Costo sistema", billBefore:"Factura actual", billAfter:"Factura con solar", envTitle:"🌱 Impacto ambiental", withoutSolar:"Sin paneles", withSolar:"Con EnerSolaris", trees:"Equivale a plantar", treesEnd:"árboles/año 🌳", reset:"← Recalcular", perMonth:"/ mes", consumDetail:"Resumen de consumo", planPanels:"paneles 500W", planGen:"Generación estimada", perDay:"/ día" },
  en:{ tag:"EN", flag:"🇺🇸", smartEnergy:"Smart Energy", title1:"CALCULATE YOUR", title2:"ENERGY SAVINGS", sub:"Design your solar system and see your monthly savings.", step1:"Step 1", step1t:"Your current bill", billLabel:"Average monthly bill", rateLabel:"Utility rate (per kWh)", rateHint:"US avg ≈ $0.13 · Hawaii ≈ $0.33 · NW ≈ $0.10", step2:"Step 2", step2t:"Your appliances", step2sub:"Select each device and customize daily usage.", addBtn:"Add", removeBtn:"Remove", hoursLabel:"Hours/day", qtyLabel:"Qty", step3:"Step 3", step3t:"Your solar location", pshLabel:"Peak sun hours per day (PSH)", pshHint:"SW US ≈ 6–7 · Midwest ≈ 4.5 · NE ≈ 3.5–4", step4:"Step 4", step4t:"Choose your solar plan", planNote:"Calculated from real consumption. Adjust manually.", calcBtn:"⚡ SEE MY SAVINGS", err:"Please enter your monthly bill", savingsMonth:"Estimated monthly savings", savingsYear:"Annual savings", savings25:"25-year savings", coverageLbl:"Solar coverage", genLbl:"Monthly generation", consumLbl:"Monthly usage", paybackLbl:"Payback period", costLbl:"System cost", billBefore:"Current bill", billAfter:"Bill with solar", envTitle:"🌱 Environmental impact", withoutSolar:"Without solar", withSolar:"With EnerSolaris", trees:"Equivalent to planting", treesEnd:"trees/year 🌳", reset:"← Recalculate", perMonth:"/ month", consumDetail:"Consumption summary", planPanels:"500W panels", planGen:"Estimated generation", perDay:"/ day" },
  pt:{ tag:"PT", flag:"🇧🇷", smartEnergy:"Energia Inteligente", title1:"CALCULE SUA", title2:"ECONOMIA DE ENERGIA", sub:"Projete seu sistema solar e veja quanto economiza por mês.", step1:"Passo 1", step1t:"Sua conta atual", billLabel:"Conta mensal média", rateLabel:"Tarifa de energia (por kWh)", rateHint:"Brasil ≈ R$0.70 · SP ≈ R$0.65 · RJ ≈ R$0.80", step2:"Passo 2", step2t:"Seus eletrodomésticos", step2sub:"Selecione cada equipamento e ajuste o uso diário.", addBtn:"Adicionar", removeBtn:"Remover", hoursLabel:"Horas/dia", qtyLabel:"Qtd", step3:"Passo 3", step3t:"Sua localização solar", pshLabel:"Horas de sol pico por dia", pshHint:"Nordeste ≈ 5.5–6.5 · Sudeste ≈ 4.5–5 · Sul ≈ 4–4.5", step4:"Passo 4", step4t:"Escolha seu plano solar", planNote:"Calculado pelo consumo real. Ajuste manualmente.", calcBtn:"⚡ VER MINHA ECONOMIA", err:"Insira sua conta mensal", savingsMonth:"Economia mensal estimada", savingsYear:"Economia anual", savings25:"Economia 25 anos", coverageLbl:"Cobertura solar", genLbl:"Geração/mês", consumLbl:"Consumo/mês", paybackLbl:"Retorno investimento", costLbl:"Custo sistema", billBefore:"Conta atual", billAfter:"Conta com solar", envTitle:"🌱 Impacto ambiental", withoutSolar:"Sem painéis", withSolar:"Com EnerSolaris", trees:"Equivale a plantar", treesEnd:"árvores/ano 🌳", reset:"← Recalcular", perMonth:"/ mês", consumDetail:"Resumo de consumo", planPanels:"painéis 500W", planGen:"Geração estimada", perDay:"/ dia" },
  fr:{ tag:"FR", flag:"🇫🇷", smartEnergy:"Énergie Intelligente", title1:"CALCULEZ VOS", title2:"ÉCONOMIES D'ÉNERGIE", sub:"Concevez votre système solaire et voyez vos économies mensuelles.", step1:"Étape 1", step1t:"Votre facture actuelle", billLabel:"Facture mensuelle moyenne", rateLabel:"Tarif électricité (par kWh)", rateHint:"France ≈ 0.25 EUR · Belgique ≈ 0.28 EUR · CH ≈ 0.21 CHF", step2:"Étape 2", step2t:"Vos appareils électriques", step2sub:"Sélectionnez chaque appareil et ajustez l'usage quotidien.", addBtn:"Ajouter", removeBtn:"Retirer", hoursLabel:"Heures/jour", qtyLabel:"Qté", step3:"Étape 3", step3t:"Votre ensoleillement", pshLabel:"Heures d'ensoleillement par jour", pshHint:"Sud France ≈ 5–6 · Paris ≈ 3.5–4 · Corse ≈ 5.5", step4:"Étape 4", step4t:"Choisissez votre plan solaire", planNote:"Calculé selon votre consommation réelle. Ajustez si besoin.", calcBtn:"⚡ VOIR MES ÉCONOMIES", err:"Entrez votre facture mensuelle", savingsMonth:"Économies mensuelles estimées", savingsYear:"Économies annuelles", savings25:"Économies sur 25 ans", coverageLbl:"Couverture solaire", genLbl:"Production/mois", consumLbl:"Consommation/mois", paybackLbl:"Retour investissement", costLbl:"Coût système", billBefore:"Facture actuelle", billAfter:"Facture avec solaire", envTitle:"🌱 Impact environnemental", withoutSolar:"Sans panneaux", withSolar:"Avec EnerSolaris", trees:"Équivalent à planter", treesEnd:"arbres/an 🌳", reset:"← Recalculer", perMonth:"/ mois", consumDetail:"Résumé consommation", planPanels:"panneaux 500W", planGen:"Production estimée", perDay:"/ jour" },
};

const CURRENCIES = {
  COP:{ symbol:"$", label:"COP", co2:0.126, systems:[18e6,28e6,40e6,55e6,75e6], defaultRate:620, rateMin:300, rateMax:1000, rateStep:10, dec:0 },
  USD:{ symbol:"$", label:"USD", co2:0.386, systems:[7500,12000,17000,24000,32000], defaultRate:0.13, rateMin:0.08, rateMax:0.35, rateStep:0.01, dec:2 },
  EUR:{ symbol:"€", label:"EUR", co2:0.233, systems:[6500,10500,15000,21000,28000], defaultRate:0.25, rateMin:0.10, rateMax:0.50, rateStep:0.01, dec:2 },
  MXN:{ symbol:"$", label:"MXN", co2:0.432, systems:[130e3,200e3,285e3,400e3,540e3], defaultRate:1.1, rateMin:0.5, rateMax:3.5, rateStep:0.1, dec:2 },
  BRL:{ symbol:"R$", label:"BRL", co2:0.074, systems:[35e3,55e3,78e3,110e3,148e3], defaultRate:0.70, rateMin:0.30, rateMax:1.20, rateStep:0.01, dec:2 },
  GBP:{ symbol:"£", label:"GBP", co2:0.193, systems:[5800,9200,13000,18500,25000], defaultRate:0.28, rateMin:0.10, rateMax:0.50, rateStep:0.01, dec:2 },
};

const PLANS = [2,3,5,7,10];

const APPLIANCE_CATS = [
  { id:"fridge", icon:"❄️", name:{es:"Nevera",en:"Refrigerator",pt:"Geladeira",fr:"Réfrigérateur"}, desc:{es:"Funciona 24h continuas.",en:"Runs 24h.",pt:"Funciona 24h.",fr:"Fonctionne 24h."}, subItems:[
    { label:{es:"Estándar 200–350L",en:"Standard 200–350L",pt:"Padrão 200–350L",fr:"Standard 200–350L"}, kw:0.18, defaultH:24 },
    { label:{es:"Grande / Side-by-side",en:"Large / Side-by-side",pt:"Grande / Side-by-side",fr:"Grand / Américain"}, kw:0.30, defaultH:24 },
  ]},
  { id:"ac", icon:"🌀", name:{es:"Aire Acondicionado",en:"Air Conditioner",pt:"Ar-condicionado",fr:"Climatiseur"}, desc:{es:"El mayor consumidor del hogar.",en:"Biggest home energy consumer.",pt:"Maior consumidor residencial.",fr:"Plus grand c
